import { Profile, Snap, Message, Desk } from '@/types';

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'user-amal',
    display_name: 'Amalraj',
    avatar: 'character1',
    department: 'Engineering',
    job_title: 'Tech Lead',
    status: 'Working',
    desk_id: 'desk-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'user-rahul',
    display_name: 'Rahul',
    avatar: 'character3',
    department: 'Engineering',
    job_title: 'Frontend Dev',
    status: 'Working',
    desk_id: 'desk-2',
    team: 'red',
    health: 100,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: 'user-anu',
    display_name: 'Anu',
    avatar: 'character2',
    department: 'Design',
    job_title: 'UI/UX Designer',
    status: 'Working',
    desk_id: 'desk-3',
    team: 'blue',
    health: 100,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'user-vishnu',
    display_name: 'Vishnu',
    avatar: 'character5',
    department: 'Product',
    job_title: 'Product Manager',
    status: 'Break',
    desk_id: 'desk-4',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: 'user-neha',
    display_name: 'Neha',
    avatar: 'character4',
    department: 'Marketing',
    job_title: 'Content Lead',
    status: 'Working',
    desk_id: 'desk-5',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'user-arjun',
    display_name: 'Arjun',
    avatar: 'character6',
    department: 'DevOps',
    job_title: 'Cloud Architect',
    status: 'Away',
    desk_id: 'desk-6',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'user-meera',
    display_name: 'Meera',
    avatar: 'character2',
    department: 'QA',
    job_title: 'Automation Eng',
    status: 'Available',
    desk_id: 'desk-7',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'user-fahad',
    display_name: 'Fahad',
    avatar: 'character1',
    department: 'Sales',
    job_title: 'Account Exec',
    status: 'Offline',
    desk_id: 'desk-8',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];

export const MOCK_DESKS: Desk[] = [
  { id: 'desk-1', office_id: 'main-office', x: 300, y: 320, label: 'Desk #1', assigned_user_id: 'user-amal' },
  { id: 'desk-2', office_id: 'main-office', x: 460, y: 320, label: 'Desk #2', assigned_user_id: 'user-rahul' },
  { id: 'desk-3', office_id: 'main-office', x: 620, y: 320, label: 'Desk #3', assigned_user_id: 'user-anu' },
  { id: 'desk-4', office_id: 'main-office', x: 780, y: 320, label: 'Desk #4', assigned_user_id: 'user-vishnu' },
  { id: 'desk-5', office_id: 'main-office', x: 300, y: 450, label: 'Desk #5', assigned_user_id: 'user-neha' },
  { id: 'desk-6', office_id: 'main-office', x: 460, y: 450, label: 'Desk #6', assigned_user_id: 'user-arjun' },
  { id: 'desk-7', office_id: 'main-office', x: 620, y: 450, label: 'Desk #7', assigned_user_id: 'user-meera' },
  { id: 'desk-8', office_id: 'main-office', x: 780, y: 450, label: 'Desk #8', assigned_user_id: 'user-fahad' },
];

export const INITIAL_SNAPS: Snap[] = [
  {
    id: 'snap-1',
    user_id: 'user-anu',
    user_name: 'Anu',
    user_avatar: 'character2',
    user_title: 'UI/UX Designer',
    text: 'Team lunch today! 🍕',
    image_url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=600&q=80',
    reactions: { '❤️': 18 },
    comments: 7,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'snap-2',
    user_id: 'user-rahul',
    user_name: 'Rahul',
    user_avatar: 'character3',
    user_title: 'Frontend Dev',
    text: 'Coffee keeps the code running ☕',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    reactions: { '❤️': 12 },
    comments: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    sender_id: 'user-rahul',
    sender_name: 'Rahul',
    sender_avatar: 'character3',
    message: 'Hey! Ready for the sprint demo?',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'msg-2',
    sender_id: 'user-anu',
    sender_name: 'Anu',
    sender_avatar: 'character2',
    message: 'Yes! The mockups are ready in Figma.',
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
];
