import { WeaponItem } from '@/types';

export const WEAPONS_CATALOG: WeaponItem[] = [
  {
    id: 'pistol',
    name: 'Tactical Pistol',
    category: 'Pistol',
    icon: '🔫',
    price: 0,
    damage: 25,
    fireRate: '150 ms',
    clipSize: 12,
    reserveAmmo: 240,
    bulletSpeed: 950,
    maxBounces: 5,
    description: 'Standard issue high-velocity sidearm with 5x wall ricochet kinetic bounce.',
    bulletColor: '#FDE047',
    badge: 'FREE • UNLOCKED',
    unlocked: true,
  },
  {
    id: 'shotgun',
    name: 'Plasma Shotgun',
    category: 'Shotgun',
    icon: '💥',
    price: 350,
    damage: 75, // 15 x 5 pellets
    fireRate: '450 ms',
    clipSize: 6,
    reserveAmmo: 120,
    bulletSpeed: 900,
    maxBounces: 4,
    description: 'Fires 5 wide-spread ricocheting plasma buckshot pellets simultaneously.',
    bulletColor: '#F97316',
    badge: 'CROWD CONTROL',
    unlocked: false,
  },
  {
    id: 'laser',
    name: 'Cyber Laser Rifle',
    category: 'Energy',
    icon: '⚡',
    price: 600,
    damage: 35,
    fireRate: '110 ms',
    clipSize: 30,
    reserveAmmo: 300,
    bulletSpeed: 1150,
    maxBounces: 8,
    description: 'Rapid cyan laser beam pulse with 8x wall ricochet velocity & armor pierce.',
    bulletColor: '#06B6D4',
    badge: 'RAPID ENERGY',
    unlocked: false,
  },
  {
    id: 'rocket',
    name: 'Rocket Launcher',
    category: 'Heavy',
    icon: '🚀',
    price: 950,
    damage: 85,
    fireRate: '800 ms',
    clipSize: 3,
    reserveAmmo: 36,
    bulletSpeed: 750,
    maxBounces: 3,
    description: 'Launches heavy explosive kinetic missiles with fiery flame trails & splash damage.',
    bulletColor: '#EF4444',
    badge: 'EXPLOSIVE BLAST',
    unlocked: false,
  },
  {
    id: 'knife',
    name: 'Tactical Katana',
    category: 'Melee',
    icon: '🗡️',
    price: 200,
    damage: 60,
    fireRate: '250 ms',
    clipSize: 999,
    reserveAmmo: 999,
    bulletSpeed: 0,
    maxBounces: 0,
    description: 'High-speed sharp carbon steel blade with wide 180° melee slash arc.',
    bulletColor: '#F8FAFC',
    badge: 'SILENT MELEE',
    unlocked: true,
  },
];
